materials:
  - name: ball_material
    kd: 0.7
    ks: 0.1
    specular_exponent: 4
    diffuse_color: [0, 165, 255]
    specular_color: [255, 255, 255]

  - name: table_material
    kd: 0.75
    ks: 0.05
    specular_exponent: 4
    diffuse_color: [102, 102, 204]
    specular_color: [255, 255, 255]

  - name: rotation_viz_material
    kd: 0.75
    ks: 0.05
    specular_exponent: 4
    diffuse_color: [255, 0, 0]
    specular_color: [255, 255, 255]
lights:
  - type: directional
    intensity: 1
    color: [255, 255, 255]
    dir: [1, 0, -3]

  - type: directional
    intensity: 1
    color: [255, 255, 255]
    dir: [-1, -1, -3]

show_rotation_viz: false
